### ISSUE TITLE
License for library

### ISSUE THREAD

**Issue by leogaggl** [NitrofMtl/TimeOut#4]
I am trying to make a few minor changes (largely to the manifest and some updates to the readme). 

However, I notice that the repository has no license assigned. @NitrofMtl can you let me know what license you would like to use for your code? I can make changes. 

But I don't want to add a license for someone else's work :-)

Thanks for the excellent work on this library so far! It was very useful. I would just like to submit it to the PlatformIO library manager as well.

**Comment by NitrofMtl** [comment]
Hi. Thanks for the comment.

It is open source, feel free to add it and make pull request, I should have it done.

Good to know for the PIO library manager, I did not knew that it exsist.


Regards.

Nitrof

**Comment by leogaggl** [comment]
Thanks - I have added license files and made some changes to ReadMe and Manifest.

I have also done the same for MicroTuple as it is a dependency. Will to the pull requests and if you're happy submit them to the PIO Library Manager.
