### ISSUE TITLE
Add null pointer check

### ISSUE THREAD

**Issue by andrea1984** [NitrofMtl/TimeOut#9]
I found 3 errors while using this library:
1) void TimeOut::cancel()
`if (TIMEOUT::UNDELETABLE == node->type)` does not check that the node is a null pointer.
This condition occurs if the cancel() function is called twice.

2) TimeOut::handler()
`TimeOut::head->callback();
  TimeOutNode *temp = TimeOut::head;
if (TimeOut::head->next)`

The TimeOut::head is a null pointer if the cancel() function is called in the callback routine of the timer.

3) Calling twice interval()/timeout() function does not change the interval/timeout, it creates another interval/timeout. Should be avoided (error and new timer not created) or handled (automatic cancel of the previous timer)

**Comment by NitrofMtl** [comment]
Hi @andrea1984 .

#1 & 2 : You right. I"ll made that fix.

#3 : Expected behavior. If you want to reset a timer, cancel it first. If you have multiple time the same timer set, you have to cancel them one at the time, FIFO.

I should add this info into the readme...

Regards.

Nitrof
